services:
  - type: web
    name: studyhelp
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT studyhelp.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_OAUTH2_KEY
        sync: false
      - key: GOOGLE_OAUTH2_SECRET
        sync: false
      - key: SOCIAL_AUTH_REDIRECT_IS_HTTPS
        value: "True"
