# Generated by Django 5.1.2 on 2026-07-25 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
