# Generated by Django 5.1.2 on 2026-07-25 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='muted_users',
            field=models.ManyToManyField(blank=True, related_name='muted_in_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='pinned_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_room', to='base.message'),
        ),
    ]
