# Generated by Django 5.1.2 on 2026-07-25 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_room_muted_users_room_pinned_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
