from django.urls import path
from . import views

urlpatterns = [
    path('login',views.loginpage,name='login'),
    path('logout',views.logoutpage,name='logout'),
    path('register',views.registerpage,name='register'),
    path('',views.home,name='home'),
    path('room/<str:pk>/',views.room,name='room'),
    path('profile/<str:pk>/',views.UserProfile,name='user-profile'),
    path('create-room/',views.CreateRoom,name='create-room'),
    path('update-room/<str:pk>/',views.UpdateRoom,name='update-room'),
    path('delete-room/<str:pk>/',views.DeleteRoom,name='delete-room'),
    path('delete-message/<str:pk>/',views.DeleteMessage,name='delete-message'),
    path('update-user/',views.UpdateUser,name='update-user'),
    path('delete-account/',views.delete_account,name='delete-account'),
    path('topics/',views.topicspage,name='topics'),
    path('activity/',views.activitypage,name='activity'),
    path('online-status/',views.online_status,name='online-status'),
    path('user/<str:pk>/badges/',views.user_badges,name='user-badges'),
    path('verify-email/<str:token>/',views.verify_email,name='verify-email'),
    path('resend-verification/',views.resend_verification,name='resend-verification'),
    path('notifications/',views.notifications_page,name='notifications'),
    path('notifications/count/',views.notifications_count,name='notifications-count'),
    path('inbox/',views.inbox,name='inbox'),
    path('dm/<str:user_id>/',views.dm_conversation,name='dm'),
    path('invite/<str:token>/',views.join_via_invite,name='join-invite'),
    path('room/<str:pk>/regenerate-invite/',views.regenerate_invite,name='regenerate-invite'),
    path('room/<str:room_pk>/mute/<str:user_pk>/',views.mute_user,name='mute-user'),
    path('room/<str:room_pk>/kick/<str:user_pk>/',views.kick_user,name='kick-user'),
    path('room/<str:room_pk>/pin/<str:msg_pk>/',views.pin_message,name='pin-message'),
    path('message/<str:pk>/react/',views.toggle_reaction,name='toggle-reaction'),
    path('room/<str:pk>/reactions/',views.room_reactions,name='room-reactions'),
    path('room/<str:pk>/messages/',views.room_messages_api,name='room-messages-api'),
    path('room/<str:pk>/search/',views.search_room_messages,name='search-room-messages'),
    path('room/<str:pk>/bookmark/',views.toggle_bookmark,name='toggle-bookmark'),
    path('bookmarks/',views.bookmarks,name='bookmarks'),
    path('room/<str:pk>/upload/',views.upload_room_file,name='upload-room-file'),
    path('file/<str:pk>/delete/',views.delete_room_file,name='delete-room-file'),
]
